version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # should exose port 5000 on port 80
      - "80:5000"
    volumes:
      - .:/usr/src/app
    #   - /usr/src/app/node_modules
